image::assets/banner.svg[Anarchy Installer's banner]

= About

Anarchy is a simple and intuitive Terminal based (TUI)
https://archlinux.org[Arch Linux] installer.
It guides you through every aspect of the installation procedure, from
partitioning to installing your favorite DE/WM.

= Installation

==== Linux

The easiest way to flash Anarchy onto a USB drive is to use `dd`:

[source,shell]
----
# Do NOT copy and paste the following, manually type the command, filling in
# the appropriate information
# Replace sdx with the name of your USB
dd if=anarchy-<version>-x86_64.iso of=/dev/sdx status=progress conv=fsync
----

If you're more comfortable with GUI programs, you can use
https://www.balena.io/etcher/[Etcher].

==== Windows

Use https://sourceforge.net/projects/win32diskimager/[Win32DiskImager] or
https://rufus.ie/[Rufus].

==== Install via SSH

> Note: Running the installer over an SSH connection requires physical access to the remote machine.

After flashing Anarchy on a USB drive, it must be booted from the machine where you want to install. If it has a wired internet connection, you only have to wait approximately one minute for Anarchy to start before connecting. If you have a wireless connection, you have two options: you normally connect to the target machine (requires physical access), or you must compile the installer yourself as indicated in the next step, but adding the file `autoconnect.sh` (it must be kept exactly the same name) along with the script `build.sh`. The `autoconnect.sh` file must have the following format:

[source,shell]
----
SSID="your_wifi_network_ssid"
PASSWORD="your_wifi_network_password"
PUBLIC_KEY=/path/to/your/public/key
----

`SSID` must contain the name that identifies the wifi network, `PASSWORD` is its respective password, and `PUBLIC_KEY` refers to the local path of our public SSH key. Then compile the installer normally.

To connect simply run on your local machine (from where you will install via SSH):

[source,shell]
----
ssh root@ip.address.of.target
----

The default password is `anarchy`.

==== Compiling the installer

Anarchy uses https://wiki.archlinux.org/index.php/archiso[Archiso] as a base.
Before starting the installation you need to have the `archiso` package
installed (`pacman -S archiso`).

To compile the installer run the `build.sh` script as root.
To see all the available compilation options run `./build.sh -h`.

= Reporting issues

Before
https://gitlab.com/anarchyinstaller/installer/issues[reporting an issue]
do the following:

* Check if you've updated Anarchy (`anarchy -u` before starting the
installation)
* Share the logs in the issue report
(Run `cat /tmp/anarchy.log | nc termbin.com 9999` in the terminal and
share the url you get returned - e.g. `https://termbin.com/xxxx`)
* If it's a post-installation issue check the
https://wiki.archlinux.org/[Arch Wiki] and
https://bbs.archlinux.org/[Arch Forums], since it's most likely an
Arch-related issue, not Anarchy's

If you don't want to sign up for Gitlab, you can also report issues
mailto:incoming+anarchyinstaller-installer-18524601-issue-@incoming.gitlab.com[over email].

= Contributing

We're always looking for new contributors to the project,
so check out our link:CONTRIBUTING.adoc[contributing guide] for more info.

= License

The project is licensed under the link:LICENSE[GNU GPLv2 license].

