#!/usr/bin/env bash

update_mirrors() {
  check_connection

  op_title="${mirror_op_msg}"

  while (true); do
    if ! edit_mirrors="$(dialog --ok-button "${ok}" --menu "\n${mirror_msg0}\n" 12 60 3 \
      "${update_mirrors_msg}" "->" \
      "${manual_mirrors}" "->" \
      "${cancel_mirrors}" "->" \
      3>&1 1>&2 2>&3)" || [ "${edit_mirrors}" == "${cancel_mirrors}" ]; then
      if (yesno "\n${mirror_cancel_msg}" "${yes}" "${no}"); then
        break
      fi
    fi

    case "${edit_mirrors}" in
    # Automatically update mirrors with reflector
    "${update_mirrors_msg}")
      log "Automatically updating mirrors"
      reflector --verbose --latest 10 --sort rate --save /etc/pacman.d/mirrorlist 3>&1 1>&2 2>&3 | log &
      pid=$! pri=1 msg="\n$mirror_load0 \n\n \Z1> \Z2reflector --latest 10 --sort rate \Zn" load
      break
      ;;

      # Manually update mirrors with a text editor
    "${manual_mirrors}")
      if ! EDITOR="$(dialog --ok-button "${ok}" --menu "${mirror_editor_msg}" 10 60 3 \
        "nano" "${nano_msg}" \
        "vim" "${vim_msg}" \
        "${cancel}" "->" 3>&1 1>&2 2>&3)" || [ "${EDITOR}" == "${cancel}" ]; then
        if (yesno "\n${mirror_cancel_msg}" "${yes}" "${no}"); then
          break
        fi
      else
        "${EDITOR}" /etc/pacman.d/mirrorlist
        break
      fi
      ;;
    esac
  done
}
